on: [push]
jobs:
  build:
    runs-on: ${{ matrix.config.os }} 
    container: bioconductor/bioconductor_docker:devel
    steps:
      - uses: actions/checkout@v1
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}
      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ runner.os }}-r-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-1-

      # This lets us augment with additional dependencies
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          apt-get update && \
          apt-get install -y --no-install-recommends \
          apt-utils \
          build-essential \
          libglpk-dev \
          libcurl4-openssl-dev \
          libmysqlclient-dev \
          libmariadb-client-lgpl-dev \
          libxml2-dev \
          libssl-dev \
          openssh-server \
          openssh-client && \
          apt-get clean && \
          rm -rf /var/lib/apt/lists/*
          Rscript -e \
          'install.packages("devtools"); 
          install.packages("R6"); 
          install.packages("magrittr"); 
          install.packages("dplyr"); 
          install.packages("stringr"); 
          install.packages("msigdbr"); 
          install.packages("rmarkdown"); 
          install.packages("RMySQL");
          install.packages("markdown");
          install.packages("DBI");
          install.packages("ontologyIndex");
          install.packages("pool");
          install.packages("getPass");
          install.packages("plyr");
          if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager");
          BiocManager::install("limma");
          devtools::install_github(repo="montilab/OmicSignature");'
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      
      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: rcmdcheck::rcmdcheck(args = c("--no-manual"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}
    matrix:
      config:
        - {os: macOS-latest, r: 'release'}
        - {os: ubuntu-18.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"}
        - {os: windows-latest, r: 'devel'}
